import Header from '@/components/share/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/share/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Frank Portfolio',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />
        <main className='flex h-[calc(100vh-400px)] flex-col items-center justify-center'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
